RealmDeactivatedError: Add redirect_domain as part of response.
This adds a new field of `redirect_domain` in the response
if the deactivated realm has any.
Also change the wording of the description for the error to
`the organization` instead of `user's organization` as it is
more generic.

Fixes #19347.